exports.USER_TYPES = {
  WALKER: 'WALKER',
  OWNER: 'OWNER',
};

exports.DAYS_OF_WEEK = {
  MONDAY: 'LUNES',
  TUESDAY: 'MARTES',
  WEDNESDAY: 'MIERCOLES',
  THURSDAY: 'JUEVES',
  FRIDAY: 'VIERNES',
  SATURDAY: 'SABADO',
  SUNDAY: 'DOMINGO',
};

exports.PET_GENDERS = {
  FEMALE: 'HEMBRA',
  MALE: 'MACHO',
};

exports.CENTER_TYPES = {
  COLONY: 'COLONY',
  SHELTER: 'SHELTER',
  DAY_CARE: 'DAY_CARE',
};

exports.RESERVATION_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED_BY_OWNER: 'ACCEPTED_BY_OWNER',
  ACCEPTED_BY_WALKER: 'ACCEPTED_BY_WALKER',
  REJECTED_BY_OWNER: 'REJECTED_BY_OWNER',
  REJECTED_BY_WALKER: 'REJECTED_BY_WALKER',
  REJECTED_BY_SYSTEM: 'REJECTED_BY_SYSTEM',
};

exports.PET_WALK_STATUS = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  FINISHED: 'FINISHED',
};

exports.JOB_TYPE = {
  PET_WALK_CREATOR: 'PET_WALK_CREATOR',
  RESERVATION_CHECKER: 'RESERVATION_CHECKER',
};

exports.PET_WALK_INSTRUCTION = {
  PICK_UP: 'PICK_UP',
  LEAVE: 'LEAVE',
};
