exports.USER_TYPES = {
  WALKER: 'WALKER',
  OWNER: 'OWNER',
};

exports.DAYS_OF_WEEK = {
  MONDAY: 'LUNES',
  TUESDAY: 'MARTES',
  WEDNESDAY: 'MIERCOLES',
  THURSDAY: 'JUEVES',
  FRIDAY: 'VIERNES',
  SATURDAY: 'SABADO',
  SUNDAY: 'DOMINGO',
};

exports.PET_GENDERS = {
  FEMALE: 'HEMBRA',
  MALE: 'MACHO',
};
