name: Github Actions CI
on:
  push:
    branches:
      - development
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: testing
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: walkie_doggie_test

    services:
      postgres:
        image: postgres:12.2
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: walkie_doggie_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.18'
      - run: npm install
      - run: npm run migrations
      - run: npm test
